color:
  $type: color
  action:
    primary:
      default:
        on-light:
          $value: "{color.red.50}"
        on-dark:
          $value: "{color.red.50}"
      hover:
        on-light:
          $value: "{color.red.50}"
        on-dark:
          $value: "{color.red.50}"
